import mongoose, { Schema } from "mongoose";
import { ReferencePerson } from "../../../../domain/entity/referencePerson";
import { rg } from "./rgModel";
import { observation } from "./observationModel";

const referencePerson = new mongoose.Schema<ReferencePerson>({
    fullName:{
        required:true,
        type:String
    },
    socialName:{
        required:true,
        type:String
    },
    motherName:{
        required:true,
        type:String
    },
    nis:{
        type:String
    },
    cpf:{
        type:String,
        required:true
    },
    diagnosis:{
        required:true,
        type:String
    },
    rg:{
        type:rg,
        required:true
    },
    isShelter:{
        required:true,
        type:Boolean
    },
    localLocalization:{
        type:String,
        required:true,
        enum:["URBAN","RURAL"]
    },
    cep:{
        type:String
    },
    adress:{
        required:true,
        type:String
    },
    neighborhood:{
        required:true,
        type:String
    },
    adressComplement:{
        required:true,
        type:String
    },
    adressNumber:{
        required:true,
        type:String
    },
    city:{
        required:true,
        type:String
    },
    phone:{
        required:true,
        type:String
    },
    state:{
        required:true,
        type:String
    },
    whoIsOpeningId:{
        type:String,
        required:true
    },
    fistEntryInUnityId:{
        type:Schema.Types.ObjectId,
        ref:'firstEntryInUnity'
    },
    familyCompositionId:{
        type:Schema.Types.ObjectId,
        ref:'familyComposition'
    },
    homeConditionsId:{
        type:Schema.Types.ObjectId,
        ref:'homeConditions'
    },
    workConditionId:{
        type:Schema.Types.ObjectId,
        ref:'workCondition'
    },
    familySituationViolationId:{
        type:Schema.Types.ObjectId,
        ref:'familySituationViolence'
    },
    helphyConditionId:{
        type:Schema.Types.ObjectId,
        ref:'helphyCondition'
    },
    eventlyBenefitId:{
        type:Schema.Types.ObjectId,
        ref:'eventlyBenefit'
    },
    familyAndCommunityId:{
        type:Schema.Types.ObjectId,
        ref:'familyAndCommunity'
    },
    familyHistoryOfComplianceSocialEducationalMensuresId:{
        type:Schema.Types.ObjectId,
        ref:'familyHistoryOfComplianceSocialEducationalMensures'
    },
    observations:[{
        type:observation
    }],
    birthDate:{
        type:Date,
        required:true
    },
    biologicalGender:{
        type:String,
        required:true
    },
    createdAt:{
        type:Date,
        default:Date.now
    },
    updatedAt:{
        type:Date,
        default:Date.now
    }
});

export const referencePersonModel = mongoose.model('ReferencePerson',referencePerson);