object RG{
        Number: Number
        String: issuingAgency
        Date: UfIssue
    }

    object housingConditions{
        Date createdAt
        Date updatedAt
        TYPE_OF_RESIDENCE typeOfResidence
        HOUSE_MATERIAL houseMaterial
        HAS_ELECTRIC_POWER hasElectricPower
        HAS_PLUMBING_WATER Boolean
        TYPE_OF_WATER_SUPPLY typeOfWaterSupply
        SEWAGE_COLLECTION sewageCollection
        GARBAGE_COLLECTION garbageCollection
        TotalNumberOfRooms Number
        TotalNumberOfBedrooms Number
        TotalNumberOfPeapleDivideTotalBedrooms Number
        HasHomeAccessibility Boolean
        HasRiskOfFloodingOrCollapse Boolean
        HasHouseholdDificultiesOfAccess Boolean
        HomeIsLocatedInAnAreaOfDangerOrViolence Boolean
        observations List<String>
    }

    object EducationalConditionsOfFamily{
        -ObjectID id
        -Date createdAt
        -Date updatedAt
        -Number nOrder
        -Number age
        -String firstName
        -Bool isLiterati
        -Bool isAtSchool
        -SOCIAL_REFERENCE_PERSON_KINSHIP kinship
        -DOCUMENTS_REQUIRED documentsRequired
        -List<String> observations
    }

    object EducationalConditions{
        Date createdAt
        Date updatedAt
        EDUCATION_CODE educationCode
        Number SchoolVunerabilityIndex
        BolsaFamiliaSchoolNoncomplianceNote bolsaFamiliaSchoolNoncomplianceNote
        SchoolVunerabilityIndex schoolVunerabilityIndex
        List<String> observations
    }

    object BolsaFamiliaSchoolNoncomplianceNote{
        Date createdAt
        Date updatedAt
        Number nOrder
        Date dateOfNoncompliance
        NoncomplianceEfects noncomplianceEfects
        bool requestsSuspensionOfTheEffect
    }