@startuml

 package "Acesso a benefícios Enventuais"{

    class Family {
            -ObjectID id
            -boolean livinInShelter
            -Date createdAt
            -Date updatedAt
            -String fullNameOfReferencePerson
            -String socialName
            -String motherName
            -Number referencePersonNIS
            -String referencePersonCPF
            -RG referencePersonRG
            -String adress
            -String adressNumber
            -String complement
            -String neighborhood
            -String CEP
            -String referenceAdressPoints
            -TYPE_LOCATION locationType
            -ENTRY_TYPE entryType
            -String whoRefered
            -String familyFirstDemand
            -ageGroup ageGroup
            -EducationalConditionsOfFamily educationalConditionsOfFamily
            -SchoolVunerabilityIndex schoolVunerabilityIndex
            -List<BolsaFamiliaSchoolNoncomplianceNote> bolsaFamiliaSchoolNoncomplianceNote
            -work_conditions work_conditions
            -Person_with_disability person_with_disability
            -bool hasBasicsActivitiesOfDailyLiving
            -bool hasFoodInsecurity
            -bool hasSeriusIllness
            -List<Benefits_access> benefits_access
            -List<person_with_serius_illness> persons_with_serius_illness
            -bool hasMemberWithControllerMedication
            -List<person_with_controller_medication> persons_with_controller_medication
            -hasAlcoholismProblem
            -List<person_with_alcoholism_problem> persons_with_alcoholism_problem
            -hasDrugAddictionProblem
            -List<person_with_drug_addiction_problem> persons_with_drug_addiction_problem
            -List<PregnantPerson> pregnantPersons
            -List<BolsaFamiliaHealthNoncomplianceNote> bolsaFamiliaHealthNoncomplianceNotes
            -map<String,dynamic> familySpecifics
            -map<String,Bool> socialBenefits
            -List<String> referencePhone
            -List<FamilyMember> familyMembers
            -List<String> observations
        }

    object Benefits_access{
        ObjectID objectID
        Date dateOfStartBenefit
        TYPE_OF_BENEFIT typeOfBenefit
        String observation
        Number nRegisterBirthRegistration
        Number nRegisterDeathRegistration
    }

    enum TYPE_OF_BENEFIT{
        birth_aid
        funeral_assistance
        specific_item_or_kit_for_emergency_situations
        basic_basket
        payment_of_rent_or_social_rent
        others
    }

    Family <-- Benefits_access
    TYPE_OF_BENEFIT --> Benefits_access
 }

@enduml