@startuml
    
    package "Composição familiar" {
        
            map "family_specifics <String,dynamic>" as familySpecifics {
                homeless_family => false
                quilombola_family => false
                ribeirinha_family => false
                gypsy_family => false
                indigenous_family_living_in_tribe => List<String,dynamic> { isIndigenous => false, nameOfTribe => "name" }
                indigenous_family_not_living_in_tribe => List<String,dynamic> { isIndigenous => false, nameOfTribe => "name" }
                others => "observations"
            }

            enum TYPE_LOCATION {
                URBANO
                RURAL
            }

            map "social_benefits <String,bool>" as socialBenefits {
                bolsa_familia => false
                BPC => false
                PETI => false
                others => false
            }

            object RG{
                Number: Number
                String: issuingAgency
                Date: UfIssue
            }

            enum ENTRY_TYPE {
                spontaneous_demand = 1
                active_team_serach = 2
                referral_from_other_service_or_unit = 3
                referral_from_other_service_or_special_unit = 4
                referral_from_health_unit = 5
                referral_from_education_unit = 6
                referral_from_others_sectoral_policies = 7
                referral_from_guardianship_council = 8
                referral_from_judicial_power = 9
                referral_from_public_security = 10
                others_referral = 11
            }

            map "age_group <String,Number>" as ageGroup {
                ZERO_TO_SIX_PEAPLE => 0
                SEVEN_TO_FOURTEEN => 0
                FIFTEEN_TO_SEVENTEEN => 0
                EIGHTEEN_TO_TWENTY-NINE => 0
                THIRTY_TO_FIFTY-NINE => 0
                SIXTY_TO_SIXTY-FOUR => 0
                SIXTY-FIVE_TO_SIXTY-NINE => 0
                SEVENTY_OR_MORE => 0
                TOTAL_OF_PEOPLE => 0
            }

            class Family {
                -ObjectID id
                -boolean livinInShelter
                -Date createdAt
                -Date updatedAt
                -String fullNameOfReferencePerson
                -String socialName
                -String motherName
                -Number referencePersonNIS
                -String referencePersonCPF
                -RG referencePersonRG
                -String adress
                -String adressNumber
                -String complement
                -String neighborhood
                -String CEP
                -String referenceAdressPoints
                -TYPE_LOCATION locationType
                -ENTRY_TYPE entryType
                -String whoRefered
                -String familyFirstDemand
                -ageGroup ageGroup
                -map<String,dynamic> familySpecifics
                -map<String,Bool> socialBenefits
                -List<String> referencePhone
                -List<FamilyMember> familyMembers
                -List<String> observations
            }

            class FamilyMember{
                -ObjectID id
                -Date createdAt
                -Date updatedAt
                -Number nOrder
                -GENDER gender
                -String birthName
                -Number age
                -SOCIAL_REFERENCE_PERSON_KINSHIP kinship
                -DOCUMENTS_REQUIRED documentsRequired
                -List<String> observations
            }

            Family -- ENTRY_TYPE
            Family -- TYPE_LOCATION
            Family -- ageGroup
            Family -- FamilyMember
            Family -- RG
            Family -- socialBenefits
            Family -- familySpecifics
    }

@enduml