@startuml

    package "Condições educacionais da familia" {

        class Family {
            -ObjectID id
            -boolean livinInShelter
            -Date createdAt
            -Date updatedAt
            -String fullNameOfReferencePerson
            -String socialName
            -String motherName
            -Number referencePersonNIS
            -String referencePersonCPF
            -RG referencePersonRG
            -String adress
            -String adressNumber
            -String complement
            -String neighborhood
            -String CEP
            -String referenceAdressPoints
            -TYPE_LOCATION locationType
            -ENTRY_TYPE entryType
            -String whoRefered
            -String familyFirstDemand
            -ageGroup ageGroup
            -EducationalConditionsOfFamily educationalConditionsOfFamily
            -SchoolVunerabilityIndex schoolVunerabilityIndex
            -List<BolsaFamiliaSchoolNoncomplianceNote> bolsaFamiliaSchoolNoncomplianceNotes
            -map<String,dynamic> familySpecifics
            -map<String,Bool> socialBenefits
            -List<String> referencePhone
            -List<FamilyMember> familyMembers
            -List<String> observations
        }      

        object EducationalConditionsOfFamily{
        -ObjectID id
        -Date createdAt
        -Date updatedAt
        -Number nOrder
        -Number age
        -String firstName
        -Bool isLiterati
        -Bool isAtSchool
        -SOCIAL_REFERENCE_PERSON_KINSHIP kinship
        -DOCUMENTS_REQUIRED documentsRequired
        -List<String> observations
        }

        object BolsaFamiliaSchoolNoncomplianceNote{
        Date createdAt
        Date updatedAt
        Number nOrder
        Date dateOfNoncompliance
        NoncomplianceEfects noncomplianceEfects
        bool requestsSuspensionOfTheEffect
        }

        map "SchoolVunerabilityIndex <String,Number> " as SchoolVunerabilityIndex{
        0_5Years_dont_go_to_school => 0
        6_14Years_dont_go_to_school => 0
        15_17Years_dont_go_to_school => 0
        10_17Years_dont_know_how_to_read_or_write => 0
        18_59Years_dont_know_how_to_read_or_write => 0
        60_MOREYears_dont_know_how_to_read_or_write => 0
    }
    }

    enum SOCIAL_REFERENCE_PERSON_KINSHIP{
        referencePerson = 1
        spouse = 2
        son = 3
        stepson = 4
        grandchild = 5
        parents = 6
        fatherInLaw = 7
        brothers = 8
        genre = 9
        otherRelative = 10
        notRelated = 11
    }
    
    

    enum DOCUMENTS_REQUIRED {
        CN
        RG
        CTPS
        CPF
        TE
    }

    enum NoncomplianceEfects{
        Advetisement
        Blocked
        Suspended
        Canceled
    }

    Family <-- EducationalConditionsOfFamily
    EducationalConditionsOfFamily <-- SOCIAL_REFERENCE_PERSON_KINSHIP
    EducationalConditionsOfFamily <-- DOCUMENTS_REQUIRED
    Family <-- SchoolVunerabilityIndex
    Family <-- BolsaFamiliaSchoolNoncomplianceNote
    BolsaFamiliaSchoolNoncomplianceNote <-- NoncomplianceEfects
    

@enduml