@startuml

    package "Condições habitacionais da família" {

        enum GARBAGE_COLLECTION {
            DIRECT_COLLECTION
            DIRECT_INCOLLECTION
            DONT_HAS
        }

        enum SEWAGE_COLLECTION {
            SEWAGE_OR_RAIN_COLLECTION_NETWORK
            SEPTIC_TANK
            RUDIMENTARY_FIT
            DIRECT_TO_DITCH_OR_RIVER_OR_LAKE_OR_SEA
            HOUSEHOLD_WITHOUT_BATHROOM
        }

        enum TYPE_OF_WATER_SUPPLY {
            GENERAL_DISTRIBUTION_NETWORK
            WELL_OR_SPRING
            WATER_CISTERN
            KITE_CAR
            OTHERS
        }

        enum HAS_ELECTRIC_POWER {
            OWN_METER
            SHARED_METER
            NO_METER
            DONT_HAS
        }

        enum HOUSE_MATERIAL {
            MASONRY_OR_PAIRED_WOOD 
            PRECARIOUS_MATERIALS
        }

        enum TYPE_OF_RESIDENCE {
            OWNED
            LEASED
            CEDED
            OCCUPIED 
        }

        object housingConditions{
            Date createdAt
            Date updatedAt
            TYPE_OF_RESIDENCE typeOfResidence
            HOUSE_MATERIAL houseMaterial
            HAS_ELECTRIC_POWER hasElectricPower
            HAS_PLUMBING_WATER Boolean
            TYPE_OF_WATER_SUPPLY typeOfWaterSupply
            SEWAGE_COLLECTION sewageCollection
            GARBAGE_COLLECTION garbageCollection
            TotalNumberOfRooms Number
            TotalNumberOfBedrooms Number
            TotalNumberOfPeapleDivideTotalBedrooms Number
            HasHomeAccessibility Boolean
            HasRiskOfFloodingOrCollapse Boolean
            HasHouseholdDificultiesOfAccess Boolean
            HomeIsLocatedInAnAreaOfDangerOrViolence Boolean
            observations List<String>
        }

        class Family {
            -ObjectID id
            -boolean livinInShelter
            -Date createdAt
            -Date updatedAt
            -String fullNameOfReferencePerson
            -String socialName
            -String motherName
            -Number referencePersonNIS
            -String referencePersonCPF
            -RG referencePersonRG
            -String adress
            -String adressNumber
            -String complement
            -String neighborhood
            -String CEP
            -String referenceAdressPoints
            -TYPE_LOCATION locationType
            -ENTRY_TYPE entryType
            -String whoRefered
            -String familyFirstDemand
            -ageGroup ageGroup
            -map<String,dynamic> familySpecifics
            -map<String,Bool> socialBenefits
            -List<String> referencePhone
            -List<FamilyMember> familyMembers
            -List<String> observations
        }

        housingConditions -- TYPE_OF_RESIDENCE
        housingConditions -- HOUSE_MATERIAL
        housingConditions -- HAS_ELECTRIC_POWER
        housingConditions -- TYPE_OF_WATER_SUPPLY
        housingConditions -- SEWAGE_COLLECTION
        housingConditions -- GARBAGE_COLLECTION
        Family <-- housingConditions
    }

@enduml