@startuml

    package "Condições de trabalho e Rendimento" {

        class Family {
            -ObjectID id
            -boolean livinInShelter
            -Date createdAt
            -Date updatedAt
            -String fullNameOfReferencePerson
            -String socialName
            -String motherName
            -Number referencePersonNIS
            -String referencePersonCPF
            -RG referencePersonRG
            -String adress
            -String adressNumber
            -String complement
            -String neighborhood
            -String CEP
            -String referenceAdressPoints
            -TYPE_LOCATION locationType
            -ENTRY_TYPE entryType
            -String whoRefered
            -String familyFirstDemand
            -ageGroup ageGroup
            -EducationalConditionsOfFamily educationalConditionsOfFamily
            -SchoolVunerabilityIndex schoolVunerabilityIndex
            -List<BolsaFamiliaSchoolNoncomplianceNote> bolsaFamiliaSchoolNoncomplianceNote
            -work_conditions work_conditions
            -map<String,dynamic> familySpecifics
            -map<String,Bool> socialBenefits
            -List<String> referencePhone
            -List<FamilyMember> familyMembers
            -List<String> observations
        }

        object "Condições de trabalho" as work_conditions{
            ObjectID id
            Date createdAt
            Date updatedAt
            String firstName
            Number age
            bool has_work_card
            WORKING_CONDITION_CODE workingCondition
            bool has_work_qualification
            String work_qualification_description
            Number monthly_income

        }

        enum WORKING_CONDITION_CODE {
            not_working
            self_employed_worker
            temporary_worker_in_rural_area
            employee_without_a_signed_document
            employee_with_a_signed_document
            domestic_worker_without_a_signed_document
            domestic_worker_with_a_signed_document
            unpaid_worker
            military_or_public_servant
            employer
            trainee
            apprentice

        }

        object family_monthly_income {
        Date createdAt
        Date updatedAt
        Number total_family_income
        Number per_capita_income_family
        bool has_social_program
        icome_by_social_programs social_program_income
        String numer_order_for_BPC
        bool has_retiree_in_family_or_pensioner
        String retiree_number_order
        Number total_family_income_with_social_program
        Number per_capita_income_family_with_social_program

    }
        
    }

    map "redimento por programas sociais" as icome_by_social_programs {
        bolsa_familia => 0
        BPC => 0
        PETI => 0
        OUTHERS => 0
    }

    Family <-- work_conditions
    work_conditions <-- family_monthly_income
    family_monthly_income <-- icome_by_social_programs
    work_conditions <-- WORKING_CONDITION_CODE

@enduml